In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Flipkart_mobile_brands_scraped_data.csv")

In [3]:
df.head()

Brand Model            Color Memory Storage  Rating  Selling Price  \
0  OPPO   A53  Moonlight Black   4 GB   64 GB     4.5        11990.0   
1  OPPO   A53       Mint Cream   4 GB   64 GB     4.5        11990.0   
2  OPPO   A53  Moonlight Black   6 GB  128 GB     4.3        13990.0   
3  OPPO   A53       Mint Cream   6 GB  128 GB     4.3        13990.0   
4  OPPO   A53   Electric Black   4 GB   64 GB     4.5        11990.0   

   Original Price  
0         15990.0  
1         15990.0  
2         17990.0  
3         17990.0  
4         15990.0

In [4]:
df['Brand'].unique()

array(['OPPO', 'HTC', 'IQOO', 'Google Pixel', 'LG', 'ASUS', 'realme',
       'GIONEE', 'Nokia', 'Apple', 'SAMSUNG', 'Lenovo', 'Motorola',
       'POCO', 'vivo', 'Xiaomi'], dtype=object)

In [5]:
mobilesbrand_dict = {}
count = 0
for i in df['Brand'].unique():
        mobilesbrand_dict[i] = count
        count = count+1

In [6]:
mobilesbrand_dict

{'OPPO': 0,
 'HTC': 1,
 'IQOO': 2,
 'Google Pixel': 3,
 'LG': 4,
 'ASUS': 5,
 'realme': 6,
 'GIONEE': 7,
 'Nokia': 8,
 'Apple': 9,
 'SAMSUNG': 10,
 'Lenovo': 11,
 'Motorola': 12,
 'POCO': 13,
 'vivo': 14,
 'Xiaomi': 15}

In [7]:
# df['Model'].unique()

In [8]:
df.head(2)

Brand Model            Color Memory Storage  Rating  Selling Price  \
0  OPPO   A53  Moonlight Black   4 GB   64 GB     4.5        11990.0   
1  OPPO   A53       Mint Cream   4 GB   64 GB     4.5        11990.0   

   Original Price  
0         15990.0  
1         15990.0

In [9]:
model_dict = {}
count = 0
for i in df['Model'].unique():
        model_dict[i] = count
        count = count+1

In [59]:
model_dict

{'A53': 0,
 'A12': 1,
 'A53s 5G': 2,
 'A33': 3,
 'A31': 4,
 'A74 5G': 5,
 'A11K': 6,
 'F17 Pro': 7,
 'A54': 8,
 'Reno6 5G': 9,
 'F17': 10,
 'A16': 11,
 'Reno5 Pro 5G': 12,
 'A15': 13,
 'A74 5G BLACK': 14,
 'Reno6 Pro 5G': 15,
 'Reno2 F': 16,
 'Reno3 Pro': 17,
 'A15s': 18,
 'A15S': 19,
 'F19 Pro': 20,
 'F19 Pro+ 5G': 21,
 'F19': 22,
 'A7': 23,
 'F5': 24,
 'A5s': 25,
 'Reno': 26,
 'Reno2 Z': 27,
 'F15': 28,
 'K1': 29,
 'A9 2020': 30,
 'Find X': 31,
 'Reno4 Pro Special Edition': 32,
 'F11': 33,
 'A5': 34,
 'Reno4 Pro': 35,
 'A5 2020': 36,
 'F3 Deepika Padukone Limited Edition': 37,
 'F1 Plus': 38,
 'A83 2018 Edition': 39,
 'F3': 40,
 'A3s': 41,
 'A83': 42,
 'K3': 43,
 'F9': 44,
 'A52': 45,
 'A71 New Edition': 46,
 'Neo 7 4G': 47,
 'A71': 48,
 'A57': 49,
 'A1K': 50,
 'A37f': 51,
 'F9 Pro': 52,
 'F19s': 53,
 'A71k': 54,
 'A9': 55,
 'F3 Plus': 56,
 'Rohit Sharma Limited Edition': 57,
 'F17 PRO': 58,
 'Hardik Pandya Limited Editon': 59,
 'Ravichandran Ashwin Limited Edition': 60,
 'F11 Pro': 

In [11]:
df.isnull().sum()

Brand                0
Model                2
Color              142
Memory              42
Storage             79
Rating               0
Selling Price        3
Original Price    1678
dtype: int64

In [12]:
df.shape

(2647, 8)

In [13]:
# droping color column and Original price column

In [14]:
df.drop(['Color','Original Price'],axis=1,inplace=True)

In [15]:
df.head(2)

Brand Model Memory Storage  Rating  Selling Price
0  OPPO   A53   4 GB   64 GB     4.5        11990.0
1  OPPO   A53   4 GB   64 GB     4.5        11990.0

In [16]:
df.dtypes

Brand             object
Model             object
Memory            object
Storage           object
Rating           float64
Selling Price    float64
dtype: object

In [17]:
df.dropna(inplace=True)

In [18]:
df.shape

(2540, 6)

In [19]:
import numpy as np

In [20]:
def convert_memory(x):
    try:
        res = float(x.split(' ')[0])
        return res
    except:
        return np.NAN
    
    

In [21]:
df.head()

Brand Model Memory Storage  Rating  Selling Price
0  OPPO   A53   4 GB   64 GB     4.5        11990.0
1  OPPO   A53   4 GB   64 GB     4.5        11990.0
2  OPPO   A53   6 GB  128 GB     4.3        13990.0
3  OPPO   A53   6 GB  128 GB     4.3        13990.0
4  OPPO   A53   4 GB   64 GB     4.5        11990.0

In [22]:
df['Memory'] = df['Memory'].apply(convert_memory)

In [23]:
df.dtypes

Brand             object
Model             object
Memory           float64
Storage           object
Rating           float64
Selling Price    float64
dtype: object

In [24]:
df['Memory']

0       4.0
1       4.0
2       6.0
3       6.0
4       4.0
       ... 
2642    4.0
2643    3.0
2644    4.0
2645    3.0
2646    4.0
Name: Memory, Length: 2540, dtype: float64

In [25]:
df.shape

(2540, 6)

In [26]:
df['Storage'] = df['Storage'].apply(convert_memory)

In [27]:
df.shape

(2540, 6)

In [28]:
df.dtypes

Brand             object
Model             object
Memory           float64
Storage          float64
Rating           float64
Selling Price    float64
dtype: object

In [29]:
df['Brand'] = df['Brand'].map(mobilesbrand_dict)
df['Model'] = df['Model'].map(model_dict)

In [30]:
df.dtypes

Brand              int64
Model              int64
Memory           float64
Storage          float64
Rating           float64
Selling Price    float64
dtype: object

In [31]:
import sklearn

In [32]:
df.head(20)

Brand  Model  Memory  Storage  Rating  Selling Price
0       0      0     4.0     64.0     4.5        11990.0
1       0      0     4.0     64.0     4.5        11990.0
2       0      0     6.0    128.0     4.3        13990.0
3       0      0     6.0    128.0     4.3        13990.0
4       0      0     4.0     64.0     4.5        11990.0
5       0      0     6.0    128.0     4.3        13990.0
6       0      1     4.0     64.0     4.4        10490.0
7       0      1     3.0     32.0     4.4         9490.0
8       0      1     3.0     32.0     4.4         9490.0
9       0      1     3.0     32.0     4.4         9490.0
10      0      1     3.0     32.0     4.4         9490.0
11      0      1     4.0     64.0     4.4        10490.0
12      0      2     6.0    128.0     4.3        15990.0
13      0      2     6.0    128.0     4.3        15990.0
14      0      1     4.0     64.0     4.4        10490.0
15      0      2     8.0    128.0     4.3        17990.0
16      0      2     8.0    128.0     4.3        17990.0
17      0      3     3.0     32.0     4.3        10490.0
18      0      4     4.0     64.0     4.3        11960.0
19      0      4     4.0     64.0     4.3        11779.0

In [41]:
inputs = df.drop('Selling Price',axis=1)

In [42]:
output = df['Selling Price']

In [35]:
from sklearn.linear_model import LinearRegression


In [36]:
df.isnull().sum()

Brand              0
Model              0
Memory           125
Storage           22
Rating             0
Selling Price      0
dtype: int64

In [37]:
df.dropna(inplace=True)

In [38]:
df.isnull().sum()

Brand            0
Model            0
Memory           0
Storage          0
Rating           0
Selling Price    0
dtype: int64

In [39]:
df

Brand  Model  Memory  Storage  Rating  Selling Price
0         0      0     4.0     64.0     4.5        11990.0
1         0      0     4.0     64.0     4.5        11990.0
2         0      0     6.0    128.0     4.3        13990.0
3         0      0     6.0    128.0     4.3        13990.0
4         0      0     4.0     64.0     4.5        11990.0
...     ...    ...     ...      ...     ...            ...
2642     15    773     4.0     64.0     4.3        12999.0
2643     15    773     3.0     32.0     4.3         9450.0
2644     15    773     4.0     64.0     4.2        12999.0
2645     15    773     3.0     32.0     4.2         9950.0
2646     15    773     4.0     64.0     4.3        12499.0

[2393 rows x 6 columns]

In [43]:
lr = LinearRegression()
lr.fit(inputs,output)

LinearRegression()

In [44]:
df.loc[20]

Brand                0.0
Model                5.0
Memory               6.0
Storage            128.0
Rating               4.3
Selling Price    18979.0
Name: 20, dtype: float64

In [45]:
lr.predict([[0,5,6,128,4.3]])

c:\users\palle\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([28901.33312067])

In [46]:
from sklearn.linear_model import Lasso


ls = Lasso()
ls.fit(inputs,output)

Lasso()

In [47]:
ls.predict([[0,5,6,128,4.3]])

c:\users\palle\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


array([28900.66380973])

In [48]:
df.loc[40]

Brand                0.0
Model               12.0
Memory               8.0
Storage            128.0
Rating               4.4
Selling Price    35990.0
Name: 40, dtype: float64

In [49]:
ls.predict([[0.0,12.0,8.0,128.0,4.4]])

c:\users\palle\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


array([28474.4977999])

In [50]:
from sklearn.ensemble import RandomForestRegressor

In [51]:
rf = RandomForestRegressor()
rf.fit(inputs,output)

RandomForestRegressor()

In [52]:
rf.predict([[0.0,12.0,8.0,128.0,4.4]])

c:\users\palle\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([34729.41666667])

In [53]:
rf.predict([[0,5,6,128,4.3]])

c:\users\palle\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([17077.83428571])

In [54]:
from sklearn.tree import DecisionTreeRegressor

In [55]:
dt = DecisionTreeRegressor()
dt.fit(inputs,output)

DecisionTreeRegressor()

In [56]:
dt.predict([[0,5,6,128,4.3]])

c:\users\palle\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([18979.])

In [57]:
dt.predict([[0.0,12.0,8.0,128.0,4.4]])

c:\users\palle\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([35990.])

In [58]:
import pickle
file1 = open('model.sav','wb')
pickle.dump(dt,file1)